name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
          dotnet --info
      - name: python Command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
        shell: powershell
      - name: Directory Bash
        run: pwd
        shell: bash
  run-after-all-successed:
    runs-on: windows-latest
    needs: [run-shell-command, run-windows-commands]
    steps:
      - name: PrintMessage
        run: echo "Everything has passed"

