name: Container
on: [push]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    # container: node:16-alpine3.15 
    container:
      image: node:16-alpine3.15
      env: 
        someVar: 22321
        somevar2: 33
      # ports: 
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
          $someVar

        
